export const ROUTES = {
    vi: {
      ['/']: "/",
      home: "/trang-chu",
      ['about-us']: "/ve-chung-toi",
      technology: "/cong-nghe",
      ['case-study']: "/du-an",
      caseStudyDetail: (slug: string) => `/du-an/${slug}`,
      ['service-solution']: "/dich-vu-giai-phap",
      contact: "/lien-he",
      product: "/san-pham",
      productDetail: (slug: string) => `/san-pham/${slug}`,
      news: "/tin-tuc",
      newsDetail: (slug: string) => `/tin-tuc/${slug}`,
      recruitment: "/tuyen-dung",
      recruitmentDetail: (slug: string) => `/tuyen-dung/${slug}`,
      error500: "/error",
    },
    en: {
      ['/']: "/",
      home: "/home",
      ['about-us']: "/about-us",
      technology: "/technology",
      ['case-study']: "/case-study",
      caseStudyDetail: (slug: string) => `/case-study/${slug}`,
      ['service-solution']: "/service-solution",
      contact: "/contact",
      product: "/product",
      productDetail: (slug: string) => `/product/${slug}`,
      news: "/news",
      newsDetail: (slug: string) => `/news/${slug}`,
      recruitment: "/recruitment",
      recruitmentDetail: (slug: string) => `/recruitment/${slug}`,
      error500: "/error",
    },
  };